### PR TITLE
Shorten regex to detect head-tag

### PR DESCRIPTION
**Pull request by imme-emosol**

### CODE REVIEW

**Comment by imme-emosol** [comment]
Hm.. may not be a good idea.

> This happens because an atom in the regexp is quantified by both an immediate + and an enclosing * with nothing to differentiate which is in control of any particular character. The nondeterminism that results produces super-linear performance. (Consult Mastering Regular Expressions (3rd ed.), pp 222, by Jeffery Friedl, for an in-depth analysis).
~ https://ruby-doc.org/core-3.0.1/Regexp.html#method-i-named_captures

**Comment by jaredmdobson** [comment]
@imme-emosol what's not a good idea, making the change or keeping the regex as is?

**Comment by imme-emosol** [comment]
I thought that making the change might cause a performance issue. But, reading https://ruby-doc.org/core-3.0.1/Regexp.html#class-Regexp-label-Performance more carefully it seems to be about the `*`, match-zero-or-more. So I guess there is no reason why the regular expression should be written the way it is in the originating branch and the change *can* be merged. My guess would also be that the changed regex will be less work for the regular expression parser, especially in cases where there's only a `<head>`.

**Comment by jaredmdobson** [comment]
Awesome, thanks for the explanation @imme-emosol :)

**Pull request merged**
